image: maven:3-jdk-8
stages:
  - build
  - test
  - deploy
  
#Job 1
maven-build:
  stage: build
  script: "mvn package -B"
  artifacts:
    paths: 
      - '/builds/Carmenjara/client-microservice-CRM/target/microservices-docker-0.0.1-SNAPSHOT.jar'
  cache:
    paths: 
      - '/builds/Carmenjara/client-microservice-CRM'

#Job 2
maven-test:
  stage: test
  script: "mvn test -B"

#Job 3
deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
  - main
