image: maven:3-jdk-8
stages:
  - build
  - test
  - deploy
  
#Job 1
maven-build:
  stage: build
  script: "mvn install -f /builds/Carmenjara/client-microservice-CRM/microservices-docker/pom.xml"
  artifacts:
    paths: 
      - '/root/.m2/repository/com/devops/microservices-docker/0.0.1-SNAPSHOT/microservices-docker-0.0.1-SNAPSHOT.jar'
  cache:
    paths: 
      - '/root/.m2/repository/com/devops/microservices-docker'

#Job 2
maven-test:
  stage: test
  script: "mvn test -B"

#Job 3 and finall
deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
  - main
